name: untitled1
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pull_to_refresh: ^2.0.0
  flutter:
    sdk: flutter
  hooks_riverpod: ^0.14.0+5
  provider: ^6.0.1   # 跨组件状态共享
  get: ^4.3.8
  fluro: ^2.0.3
  flutter_swiper_plus: ^2.0.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_fancy_tree_view: ^0.5.1+1  #tree
  common_utils: ^2.0.2 #工具类 时间、日期、日志等
  flustars: ^2.0.0 #flustars库为大家提供更多的工具类，例如SpUtil，ScreenUtil, DirectoryUtil等等
  flutter_html: ^0.8.2 #静态html标记呈现为Flutter小部件
  # flutter_advanced_networkimage: ^0.7.0 #图片组件 弃用 版本老旧，与较多存在冲突，现有：flustars,dio冲突
  dio: ^4.0.0 #dio是一个强大的Dart Http请求库，支持Restful API、FormData、拦截器、请求取消、Cookie管理、文件上传/下载、超时、自定义适配器等
  image_picker: 0.8.4+4 #
  extended_image: ^5.1.3 #强大的官方 Image 扩展组件, 支持加载以及失败显示，缓存网络图片，缩放拖拽图片，图片浏览(微信掘金效果)，滑动退出页面(微信掘金效果)，编辑图片(裁剪旋转翻转)，保存，绘制自定义效果等功能
  flutter_easyrefresh: ^2.2.1 #EasyRefresh很容易就能在Flutter应用上实现下拉刷新以及上拉加载操作，它支持几乎所有的Flutter控件。
  liquid_pull_to_refresh: ^3.0.0  #下拉更新组件  简易
  cookie_jar: ^3.0.1 
  shared_preferences: ^2.0.8 #本地缓存
  scoped_model: ^2.0.0-nullsafety.0 
  dio_http2_adapter: ^2.0.0 
  dio_cookie_manager: ^2.0.0 #cookieManager ,依赖于cookie——jar
  fluttertoast: ^8.0.8 #弹窗工具

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - static/images/supwit.png
    - static/images/login.jpg
    - static/images/collect.png
    - static/images/expand.png
    - static/images/member.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
